# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [Src, Lib, Visual Studio Integration]

markdown: redcarpet
encoding: UTF-8
highlighter: pygments

# Site settings
title: CatAmo凉生
email: bingjie.gao10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: /TempBlogs/ # the subpath of your site, e.g. /blog
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://catamo10.github.io/TempBlogs/" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
# twitter_username: jekyllrb
jianshu_username: CatAmo凉生_简书
github_username:  CatAmo10
jianshu_png: /TempBlogs/_includes/skeleton.png

gems: [jekyll-paginate]
paginate: 3
paginate_path: "blog/page:num"
# Build settings
# markdown: kramdown 
# kramdown: 
# input: GFM

