# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
exclude: [Src, Lib, Visual Studio Integration]

markdown: redcarpet
encoding: UTF-8
highlighter: pygments

# Site settings
title: CatAmo凉生
email: bingjie.gao10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: /TempBlogs/ # the subpath of your site, e.g. /blog
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

gems: [jekyll-paginate]
paginate: 3
paginate_path: "blog/page:num"
# Build settings
# markdown: kramdown 
# kramdown: 
# input: GFM

